moltimate/moltimate-frontend

src/components/search/results/protein/ngl-temp-util.js
This fixes a missing visualization issue that happens if you have up to date frontend and backend locally
=> Make data fit new naming from backend

src/components/protein/ngl-util.js
Alignment stopped showing in the frontend. Moved our old view file to where it seems the new location is. Also changed the colors to match the alignment on the splash page. Took colors from here: https://github.com/moltimate/moltimate-frontend/blob/master/src/components/landing/styles.js#L126-L130
=> Bring back alignments and fix colors

src/builder/BuilderContainer.js, src/common/ResultItem.js, src/common/ResultsBox.js, src/util/request.js
Disable click no failed result
=> Failed result

LICENSE, package.json
Added the GPL 2.0 license to match the back-end repository, and
fixed some version and project typos in package.json
=> Licensing and package.json fixes

package.json, src/protein/ProteinContainer.js, src/protein/ngl-util.js, src/settings/DisplayMode.js, src/settings/SettingsContainer.js
Added several new protein display types. Added set of radio buttons for ligands.
=> Merge MOL-47 into change display mode branch

src/protein/ngl-util.js
Stage is no longer created an additional time when loading a molecule with the same child and parent ID. This fixes the duplication bug.
=> Merge MOL 43 into dev

.travis.yml
Disable email notifications on successful builds
=> Disabling Travis build notifications on front-end

src/DummyData.js, src/MoltimateContainer.js, src/TopBar.js, src/common/FilteredLigandResults.js, src/common/FilteredResultsBox.js, src/common/LigandResultItem.js, src/common/LigandResultsBox.js, src/common/styles.js, src/docking_info/DockingInfoContainer.js, src/docking_info/LigandDetailsBox.js, src/docking_info/styles.js, src/imported_ligands/ImportedLigandsContainer.js, src/ligand_library/LigandLibraryContainer.js, src/settings/DockingSearchBounds.js, src/settings/SettingsContainer.js, src/settings/styles.js
The primary UI updates necessary for integrating docking into the Moltimate app. Includes:
- Settings Pane
- Docking Range
- Ligand Library
- Contains dummy data
- Imported Ligands
- Upload Ligands button
- Filtering bar
=> Mol 18 docking ui

.gitignore, README.md, src/DummyData.js, src/MoltimateContainer.js, src/TopBar.js, src/protein/DockingContainer.js, src/protein/ngl-util.js
Merged in changes from MOL-49-Visualization
=> Merge MOL-49-Visualization into dev

src/MoltimateContainer.js, src/protein/DockingContainer.js, src/protein/ProteinContainer.js, src/protein/ngl-util.js, src/settings/DisplayMode.js, src/settings/SettingsContainer.js, src/settings/styles.js, src/util/request.js
Adds the ability to modify the display mode of both proteins when doing alignment and each part of the structure when performing docking. Includes all changes related to display mode modification from the [change-display-mode](https://github.com/moltimate/moltimate-frontend/tree/change-display-mode) branch that we forgot to merge in.
=> Merge MOL-68 into dev

package.json, webpack.config.js
Added watchOptions to webpack, for polling of changes and auto-refresh while running locally
=> Webpack watch config

src/MoltimateContainer.js, src/common/LigandResultItem.js, src/common/ResultsBox.js, src/docking/DockingContainer.js, src/ligand_library/LigandLibraryContainer.js, src/search/SearchContainer.js, src/util/request.js
The Ligand Library will now automatically load from the backend. Loading will occur directly after alignment has been performed, as that is when we know the Electron Class of the searched proteins. Each protein in the search box will show up in the list, and each ligand in the list has a hover text that states its associated protein and smiles string.
=> Merge Ligand Library into Integrate-Visualization

package.json, src/common/ResultsBox.js, src/search/SearchContainer.js
Added filtering options for the search results on the protein alignment
=> Molt-63 Filter Search Results

src/common/MenuCard.js, src/common/Modal.js, src/common/styles.js, src/search/SearchContainer.js, src/search/SearchText.js, src/search/form/QueryFormContainer.js, src/search/form/styles.js
Adding tooltips to the labels/buttons in the search box.
Adding a Modal to search box, that will display info helpful for its use.
- [X ] Code compiles correctly
- [X ] All tests passing
- [X ] Extended the README / documentation, if necessary
=> Mol 70 search tooltips and modal

src/MoltimateContainer.js, src/builder/BuilderContainer.js, src/builder/form/BuilderForm.js, src/builder/form/ProteinOptions.js, src/builder/form/TestOptions.js, src/builder/styles.js, src/common/FilteredLigandResults.js, src/common/MenuCard.js, src/common/Modal.js, src/common/ParsedToolTip.js, src/common/ResultsBox.js, src/common/styles.js, src/docking/DockingContainer.js, src/helpText.js, src/imported_ligands/ImportedLigandsContainer.js, src/ligand_library/LigandLibraryContainer.js, src/search/SearchContainer.js, src/search/form/QueryFormContainer.js, src/search/form/styles.js
Adding tool tips/Modals to the rest of the menu items
=> [MOL-142] all menu items tooltips/modals

src/MoltimateContainer.js, src/search/SearchContainer.js, src/settings/SettingsContainer.js
=> Mol 158 hide ligand UI components

src/builder/form/TestOptions.js, src/search/form/QueryFormContainer.js, src/util/request.js
=> Mol 138 protein files not searched

src/common/ResultsBox.js
=> [MOL-220] filter all results -dev

src/MoltimateContainer.js, src/search/SearchContainer.js
=> No ticket adding docking

src/common/styles.js, src/docking_info/LigandDetailsBox.js
Updating Units in table and changing text color of ligand that is mid docking
=> Mol 248 docking UI improvements

src/common/ResultDetails.js
=> Fixed formats for active sites

src/docking_info/LigandDetailsBox.js
=> Docking result table resized
